cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "git"
brew "python"
brew "neofetch"
brew "jq"
brew "vim"
brew "htop"
brew "tree"
brew "rsync"
brew "wget"
brew "n"
brew "openjdk"
brew "translate-shell"

cask "google-chrome"
cask "google-japanese-ime"
cask "yt-music"
cask "docker"
cask "wezterm"
cask "zoom"
cask "discord"
cask "slack"
cask "balenaetcher"
cask "tiles"
cask "microsoft-teams"
cask "microsoft-office"
cask "visual-studio-code"
cask "vlc"
