#!/bin/sh

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_CURRENT_SESSION=sway
# XDG_RUNTIME_DIR=/tmp
export DESKTOP_SESSION=sway
export QT_QPA_PLATFORM="wayland;xcb"
# GDK_DPI_SCALE=1
# QT_SCALE_FACTOR=1
export MOZ_ENABLE_WAYLAND=1
# export ELECTRON_OZONE_PLATFORM_HINT=wayland
# MOZ_DBUS_REMOTE=1
export WINIT_UNIX_BACKEND=x11
export XDG_SCREENSHOTS_DIR=$HOME/Pictures/screenshots
export LIBSEAT_BACKEND=logind
# export QT_IM_MODULE=fcitx
# export GTK_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export DefaultIMModule=fcitx
export INPUT_METHOD=fcitx
export XCURSOR_PATH=${XCURSOR_PATH}:~/.icons
if [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
    # /usr/bin/pipewire &
    # /usr/bin/pipewire-pulse &
    exec dbus-run-session sway
fi
