name: "Void"
on: [push]
jobs:
  void:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-glibc:latest
    defaults:
      run:
        shell: sh
    steps:
      - name: Install repositories
        run: xbps-install -Sy void-repo-multilib void-repo-multilib-nonfree void-repo-nonfree
      - name: Install build dependencies
        run: xbps-install -Sy libstdc++ libstdc++-32bit
      - uses: actions/checkout@v3
      - name: Setup Void
        run: make all
