name: "Void"
on: [push]
jobs:
  void:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-glibc:latest
    defaults:
      run:
        shell: sh
    steps:
      - name: Install required packages
        run: xbps-install -S libstdc++ libstdc++-32bit
      - uses: actions/checkout@v3
      - name: Setup Void
        run: make all
